name: Build Android Codex

on:
  push:
    branches:
      - v0

jobs:
  build_android_app:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3.1.0

      - name: Setup java
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2.3.3

      - name: Install tabris-cli
        run: npm install -g tabris-cli

      - name: Install application dependencies
        run: |
          npm run --if-present prepare
          npm install

      - name: Execute build
        run: |
          tabris build --release android -- --packageType=bundle

      - name: Sign release app bundle
        uses: r0adkll/sign-android-release@v1.0.4
        id: sign_app
        with:
          releaseDirectory: build/cordova/platforms/android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_APP_BUNDLE_SIGNING_KEY }}
          keyStorePassword: ${{ secrets.ANDROID_APP_BUNDLE_KEYSTORE_PASSWORD }}
          alias: ${{ secrets.ANDROID_APP_BUNDLE_KEY_ALIAS }}
          keyPassword: ${{ secrets.ANDROID_APP_BUNDLE_KEY_PASSWORD }}

      - name: Store signed app bundle
        uses: actions/upload-artifact@v3.1.1
        with:
          name: signed-app-bundle
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
          retention-days: 7
          
      - name: Codex Editor Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "0.3.0-20240901-rc"
          prerelease: true
          title: "Release 0.3.0-rc"
          files: |
            ${{ steps.sign_app.outputs.signedFile }}
